name: testing
on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-lastest

    strategy:
      matrix:
        node-version: [15.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Install and build
        run: yarn add && yarn run build

      - name: Deploy
